### ISSUE TITLE
Update Agent URLs from SmartAPI registration for Status Page

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#103]
Noel Southall (Link Broker)  10:58 AM
Wanted to follow-up about that ARS status page error for ARAX --- currently, I was using a very old snapshot from SmartAPI, so we updated it.
However, we list the endpoint for the ARAX agent in ARS as: https://arax.ncats.io/devED/api/arax/v1.0/query?bypass_cache=false
and that SmartAPI entry that you pointed me to lists:
https://arax.ncats.io/api/arax/v1.0
So, that's another problem with the current mapping. Should we further update the ARS registration for the ARAX agent to this SmartAPI url?

Eric Deutsch (Expander Agent)  10:59 AM
yes please!
If we update info in our SmartAPI registration, should we also let you know?
Or is the new information pulled automatically?

Noel Southall (Link Broker)  11:02 AM
Well, we hadn't completely settled on where the best metadata is in the SmartAPI entry .... so I was linking it on URL, but that's clearly not a good idea. Can I update the agent name to map to the SmartAPI resource name too - then I might be able to catch updates to a URL?

**Comment by edeutsch** [comment]
As you say, the SmartAPI entry (by which I assume you mean the "servers" tag):
https://arax.ncats.io/api/arax/v1.0
To this, you need to append the desired endpoint which is /query (or /predicates if you want that information)
