### ISSUE TITLE
ARS status page registration for gentics KP

### ISSUE THREAD

**Issue by marcdubybroad** [NCATSTranslator/Relay#104]
v1.0 API is the following
https://smart-api.info/ui/99592dd5fc3a69d3ed27692f3f278e47

Thanks,
Marc Duby

**Comment by MarkDWilliams** [comment]
I believe this is resolved along with molepro here, but let me know if there are any problems. 
https://github.com/NCATSTranslator/Relay/pull/107

**Comment by sstemann** [comment]
@marcdubybroad do you notice any other issues with the ARS registration?

**Comment by sstemann** [comment]
@marcdubybroad if we don't hear otherwise, we'll close this issue on Tues 2/16

**Comment by marcdubybroad** [comment]
Please close. I verified a query and all looked good on the ARS status page for our KP entry.
