### ISSUE TITLE
Suggestion: ARS designed to allow ReasonerStdAPI to be received incrementally from ARA's

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/Relay#11]
- Motivation: UX/UI studies show that if an end user needs to wait longer than some short amount of time (say, 0.5 seconds), then they will get frustrated with the system _unless_ they are aware of what is happening in the background while they wait for their results.

- ReasonerStdAPI already has a `log` feature that ARAs utilize to show their reasoning steps.

- If ARA's can share with the ARS this `log` and/or partial results in ReasonerStdAPI (instead of waiting until the very end after all reasoning has taken place), then the eventual ARS GUI can take advantage of this to show the end user "what's happening in the background" as they wait for results.

- As an additional bonus, the ARS having access to this information as it comes in will demonstrate to an end user how integrated the system as a whole has become.

Note: this feature request is motivated by a discussion with @edeutsch, @MarkDWilliams and Christine Colvis at the April 2020 Kickoff Relay.

**Comment by caodac** [comment]
Hi @dkoslicki, can you point me an example of using the `log` feature? Also, can you also let me know if I can run this [query](https://github.com/NCATSTranslator/Relay/blob/master/tr_sys/tr_ars/ars_query.json) against your ARA right now? If so, can you give me the endpoint? I'd like to incorporate it into the current running example. Thanks.

**Comment by edeutsch** [comment]
Hi Trung, regarding your question above, you can access an example of a Message with a log with this:
set ENDPOINT = 'https://arax.rtx.ai/api/rtx/v1'
curl -s -X GET --header 'Accept: application/json' $ENDPOINT/message/2020

We are also working on a system that provides real-time access to progress as a stream. You can experiment with that with something like this:
cat > query1.json
{
  "asynchronous": "stream",
  "message": {
    "query_graph": {
      "edges": [
        {
          "id": "qg2",
          "source_id": "qg1",
          "target_id": "qg0",
          "type": "physically_interacts_with"
        }
      ],
      "nodes": [
        {
          "id": "qg0",
          "name": "acetaminophen",
          "desc": "A member of the class of phenols that is 4-aminophenol in which one of the hydrogens attached to the amino group has been replaced by an acetyl group.",
          "curie": "CHEMBL.COMPOUND:CHEMBL112",
          "type": "chemical_substance"
        },
        {
          "id": "qg1",
          "desc": "Generic protein",
          "type": "protein"
        }
      ]
    }
  },
  "max_results": 100
}
^D

set CONTENT = `cat query1.json`

curl -s -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d "$CONTENT" $ENDPOINT/query

Each line (except the last) is a logging message about progress. The very last line is the returned Message.

What do you think?

**Comment by southalln** [comment]
implementation of solutions to https://github.com/NCATSTranslator/Relay/issues/42 allows this now
Reasoner service can either 1) use the callback provided in the initial query post (as many times as desired) NOTE: this uses a convention that has not yet been added to the Reasoner API v1.1 https://github.com/NCATSTranslator/ReasonerAPI/pull/150

or 2) capture the message primary key UUID from the ARS response to an initial message POST and use that for additional callbacks at /ars/api/messages/UUID

**Comment by sstemann** [comment]
https://github.com/NCATSTranslator/ReasonerAPI/pull/147
https://github.com/NCATSTranslator/ReasonerAPI/pull/150

**Comment by sstemann** [comment]
pending TRAPI v1.1
