### ISSUE TITLE
Actor update is horribly broken

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#111]
POSTing to, e.g. 

curl -d @tr_sys/tr_ars/actor_update.json http://localhost:8000/ars/api/actors > response2.htm

will only create new actors instead of updating them. You can use the Django admin interface in the interim, but delete/update for actors/agents should be fixed.

**Comment by sstemann** [comment]
current workaround: admin django interface

**Comment by sstemann** [comment]
can update through admin console or code
