### ISSUE TITLE
Seems to be extra leading h in genetics provider url in ARS status page

### ISSUE THREAD

**Issue by marcdubybroad** [NCATSTranslator/Relay#113]
From the Last Message link in the https://ars.transltr.io/ars/app/status page:

 "logs": [ "No connection adapters were found for 'hhttps://translator.broadinstitute.org/genetics_provider/trapi/v1.0/query'", "Tr_ars.url: hhttps://translator.broadinstitute.org/genetics_provider/trapi/v1.0/query" ] }, "url": "hhttps://translator.broadinstitute.org/genetics_provider/trapi/v1.0/query", "ref": "b589286f-5d74-412c-b506-a68d1fed324b" } }

hhttps://translator.broadinstitute.org/genetics_provider/trapi/v1.0/query
should be
https://translator.broadinstitute.org/genetics_provider/trapi/v1.0/query

**Comment by MarkDWilliams** [comment]
I believe this was resolved in a hotfix, though previous runs may show the incorrect URL in the logs.  We'll be doing an overhaul of the actor/agent registration and update process which was responsible for much of the trouble surrounding this.
https://ars.transltr.io/ars/api/actors/ now shows the correct URL

**Comment by MarkDWilliams** [comment]
Strange, despite this being correct in the actors registration, it does still show incorrectly in the logs.  This issue will require further investigation and is possibly related to https://github.com/NCATSTranslator/Relay/issues/111

**Comment by southalln** [comment]
The agent service itself has the wrong path https://ars.transltr.io/kp-genetics/api/

**Comment by southalln** [comment]
Fixed and released to prod
