### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/Relay#114]
Would you add CORS support in the ARS?
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET, POST, OPTIONS
```

**Comment by MarkDWilliams** [comment]
I believe support for this has been added in our dev instance https://ars-dev.transltr.io/ and we'll have it in master soon if there are no issues in dev.

**Comment by southalln** [comment]
CORS support appears to be working ... let me know if I'm incorrectly testing this 
`curl --verbose --request OPTIONS https://ars-dev.transltr.io/ars/api/actors/ --header 'Origin: http://localhost:9292' --header 'Access-Control-Request-Headers: Origin, Accept, Content-Type' --header 'Access-Control-Request-Method: GET'`

**Comment by edeutsch** [comment]
Great, thanks! It does appear now that CORS is working for https://ars-dev.transltr.io/ars/api/actors/. Would you replicate to production then too? thanks!

**Comment by southalln** [comment]
check --- I've verified and am closing the issue
