### ISSUE TITLE
Commit Testable Queries to Architecture Repo

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#120]
@patrickkwang mentioned having testable queries for the KPs that are hooked up to Strider, and that he could commit those and some simple python code for testing to the [Architecture repo](https://github.com/NCATSTranslator/TranslatorArchitecture) .  Once that is done, I will also add the Fix It queries, the ARA status queries, and the user [engagement queries ](https://github.com/NCATSTranslator/Relay/issues/84)

**Comment by patrickkwang** [comment]
https://github.com/NCATSTranslator/testing

**Comment by MarkDWilliams** [comment]
https://github.com/NCATSTranslator/testing/pull/1
