### ISSUE TITLE
ARS Testing Framework

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#130]
Work in progress at https://github.com/NCATSTranslator/testing/tree/arsTestsMDW to get testing software for the ARS and its registered services.  The following features have been requested

- Test that services have returned >0 ✅ 
- Test that a specific result is returned
- Test that a specific result is returned within the top N results
- Test that a specific result is **not** returned
- Automated github issue creation based on the results of these tests (this should be tested first in a throwaway repo)

**Comment by sstemann** [comment]
@MarkDWilliams i'm adding this here because i guess i never created my draft ticket - but could we get all of this information into an automated report:

https://docs.google.com/spreadsheets/d/1Y2yfUFl2SIgv5KkyxdQB94UE3HtVdJNJ7KdnwQgZcYI/edit?usp=sharing
