### ISSUE TITLE
Decentralize Celery, Django, and RabbitMQ

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#142]
We’re currently running everything (that is, Celery, Django, and Rabbitmq) all on the same server and they communicate with each other over local host.  In the containerized model, they would need to be running separately.  So, ITRB needs config files for us for those things set up such that they can all still talk to each other when they’re each running in their own pod.

**Comment by MarkDWilliams** [comment]
This has been accomplished
