### ISSUE TITLE
Add imProving Agent 1.1

### ISSUE THREAD

**Issue by brettasmi** [NCATSTranslator/Relay#148]
imProving Agent and SPOKE-KP are available to add to the ARS-dev.

http://smart-api.info/registry?q=1f90616a822ecd18fff70d6e518614a7
http://smart-api.info/registry?q=7f70cdfaeb801501da08dacc294e8b9f

With default query settings, they're doing pretty much the same thing right now, so you may only want to add imProving Agent for now.

**Comment by MarkDWilliams** [comment]
@brettasmi , taking a look at this now.  When I try to run the default query through the smart-api registry, I get a CORS error.  Not sure this would happen from the ARS as well, but I suspect it might.  Is CORS deliberately disabled for security purposes, and if not could it be enabled?

**Comment by brettasmi** [comment]
Hi Mark, I'm working on getting this working for SmartAPI. I don't think it will be an issue for the ARS at this point in time, as the configuration should be the same as the improving agent 1.0, which I believe works with the ARS. I think it could become an issue once the ARS has a proper web UI for the query itself.

I'll keep working on the CORS issue for SmartAPI and will let you know when I've made some progress.

**Comment by MarkDWilliams** [comment]
Gotcha, your new endpoint has been merged and deployed to http://ars-dev.transltr.io/ let me know if there are any issues.
