### ISSUE TITLE
Remote entry on service different than actor registration

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#155]
https://ars-dev.transltr.io/ara-arax/api/
"remote": "https://arax.ncats.io/api/arax/v1.1/query",

https://ars-dev.transltr.io/ars/api/actors
            "name": "ara-arax-runquery",
            "channel": "general",
            "agent": "ara-arax",
            "remote": "https://arax.rtx.ai/api/rtx/v1/query",

Note that the two arax remote entries are pretty different. How is this happening? The ara-arax service seems to be correct, and that is not the one accessible from the http://ars-dev.transltr.io/admin/tr_ars/actor/2/change/ interface

**Comment by southalln** [comment]
see also https://github.com/NCATSTranslator/Relay/issues/103

**Comment by MarkDWilliams** [comment]
I've tried bouncing the whole stack, doing migrations, etc and none of that seems to have had an effect.  All the entries (that have been changed recently) in the /actors endpoint seem to be out of date, but thankfully I've confirmed that the queries are actually being sent to the correct location.  I will investigate this further.

**Comment by sstemann** [comment]
see #175
