### ISSUE TITLE
Exposures ICEES+ registration with ARS

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Relay#171]
This issue is to request ARS registration of the ICEES+ asthma instance and the ICEES+ DILI instance. Both are TRAPI 1.1 compliant and registered with SmartAPI. The asthma instance has been TRAPI 1.1 compliant since before the May relay, but the SmartAPI registration and/or ARS registration broke post relay. We have since fixed this issue, so ARS registration can proceed for both endpoints.

**Comment by karafecho** [comment]
@MarkDWilliams @sstemann : You likely saw my email regarding the new ICEES+ DILI instance that does not require an API key. Both the ICEES+ DILI instance and the ICEES+ asthma instance have been registered with SmartAPI. Please complete the registration with the ARS, or otherwise let me know how to complete this task myself. Thanks!

**Comment by patrickkwang** [comment]
@sstemann Those are correct. We're working on differentiating the titles, and I will check on the examples. Thanks for the heads up!

**Comment by karafecho** [comment]
Sarah, just to clarify, the first registration listed above is for the ICEES+ asthma instance. Thanks!

**Comment by MarkDWilliams** [comment]
I was able to execute the examples via curl.  There was an odd delay at first, but it seems to be resolved and working quickly for the normal ICEES.  Am I correct in understanding that y'all would like two separate registrations? One for ICEES and one for ICEES DILI?

**Comment by karafecho** [comment]
Looping in @xu-hao ...

Yes, we would like two ARS registrations, one for ICEES+ asthma and one for ICEES+ DILI. We will be sure to get the naming issues worked out ASAP. Thanks for your help.

**Comment by MarkDWilliams** [comment]
Got it, I have both registered now under the names "icees" and "icees dili" but those can be changed

**Comment by karafecho** [comment]
Great! Thanks for your help, Mark.
