### ISSUE TITLE
Actor API registrations not reflecting current content

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#175]
https://ars.transltr.io/ars/api/actors
https://ars.ci.transltr.io/ara-arax/api/

>         "model": "tr_ars.actor",
>         "pk": 2,
>         "fields": {
>             "name": "ara-arax-runquery",
>             "channel": "general",
>             "agent": "ara-arax",
>             "remote": "https://arax.rtx.ai/api/rtx/v1.0/query",
>             "path": "http://ars.transltr.io/ara-arax/api/runquery",
> 

            
However, the ars is actually executing against arax 1.1 as intended:
           https://ars.transltr.io/ars/api/messages/419a9706-8cca-4f3e-80c8-17024866d17e

>             "data": {
>             "context": "https://raw.githubusercontent.com/biolink/biolink-model/master/context.jsonld",
>             "datetime": "2021-06-11 23:40:17",
>             "description": "Normal completion",
>             "id": "https://arax.ncats.io/api/arax/v1.1/response/12299",

**Comment by sstemann** [comment]
using #155
