### ISSUE TITLE
CI Status Page showing incorrect status

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#176]
https://ars.ci.transltr.io/ars/app/status

Status	 Service outage	 Service outage
Name	ara-aragorn / general	ara-arax / general
Last Reported Status	Unknown	Unknown
Average Response Time (s)	0	0
Last message	0 results	71 results
Message link		https://ars.ci.transltr.io/ars/api/messages/ac098121-fdb5-4902-b99c-0fa14a3b59c5

Message link for arax is correct, however, that message shows a completion of the query and it running without error. Something is broken in the status page logic for rendering / and exception is being thrown on parsing the json response

**Comment by MarkDWilliams** [comment]
We should deprecate the status page.

**Comment by MarkDWilliams** [comment]
Endpoint removed
