### ISSUE TITLE
ICEES+ DILI actor missing in CI, prod

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#181]
Despite this commit to master https://github.com/NCATSTranslator/Relay/commit/a3169e55615525b203309c9d327cd66255137f39 I see the ICEES+ DILI endpoint registered on https://ars-dev.transltr.io/ars/api/actors but not https://ars.transltr.io/ars/api/actors or https://ars.ci.transltr.io/ars/api/actors .... I see it correctly listed in settings.py INSTALLED_APPS ... I am not sure why it is not showing up in prod or ci.

**Comment by southalln** [comment]
See also https://github.com/NCATSTranslator/Relay/issues/171

**Comment by MarkDWilliams** [comment]
They should now be appearing in prod (the instance just wasn't running the most up to date code).  Not sure what the issue in the CI environment is as it appears to be down at the moment, but I am about to meet with ITRB and will find out.

**Comment by MarkDWilliams** [comment]
I spoke with @mapleknight about this, and it is potentially due to an issue with version control of the database in the CI environment.  The CI environment is expected to be back up today or tomorrow, and after that, I should be able to take steps to resolve this.
