### ISSUE TITLE
TextMiner queries sent to BTE

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#182]
In this AM's standup TextMining give 1 results in the ARS however when direct querying for TextMining gives 0 - it also looks like the ARS Text Mining is actually BTE.

Parent PK:
https://ars.ci.transltr.io/ars/api/messages/fea0204b-d141-4741-9686-c37ddac1881c?trace=y
TextMiner actor:
https://ars.ci.transltr.io/ars/api/messages/41b8ff82-d3bf-4a8e-b660-06196f71ceff

           "logs": [
                {
                    "timestamp": "2021-07-19T17:43:07.137Z",
                    "level": "DEBUG",
                    "message": "BTE identified 2 QNodes from your query graph",
                    "code": null
                },
                {
                    "timestamp": "2021-07-19T17:43:07.137Z",
                    "level": "DEBUG",
                    "message": "BTE identified 1 QEdges from your query graph",
                    "code": null
                },
                {
                    "timestamp": "2021-07-19T17:43:07.137Z",
                    "level": "DEBUG",
                    "message": "BTE identified your query graph as a 1-depth query graph",
                    "code": null
                },
                {
                    "timestamp": "2021-07-19T17:43:07.243Z",
                    "level": "DEBUG",
                    "message": "REDIS cache is  enabled.",
                    "code": null
                },
                {
                    "timestamp": "2021-07-19T17:43:07.244Z",
                    "level": "DEBUG",
                    "message": "BTE find cached results for e0",
                    "code": null
                },
                {
                    "timestamp": "2021-07-19T17:43:07.244Z",
                    "level": "DEBUG",
                    "message": "query_graph_handler: Post-query predicate restrictions: [].",
                    "code": null
                },
                {
                    "timestamp": "2021-07-19T17:43:07.244Z",
                    "level": "DEBUG",
                    "message": "query_graph_handler: Successfully applied post-query predicate restriction: 1 down to 1 results.",
                    "code": null
                }
            ]
        },
        "url": "https://api.bte.ncats.io/v1/smartapi/978fe380a147a8641caf72320862697b/query",
        "ref": "fea0204b-d141-4741-9686-c37ddac1881c"
    }
}

**Comment by MarkDWilliams** [comment]
https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1627493317101300
This issues seems to have resolved.
