### ISSUE TITLE
ARS Handling 500 vs 400 Errors

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#186]
I think some work needs to be done on the ARS to handle this nicely. This is related to (although not entirely the same as):
https://github.com/NCATSTranslator/minihackathons/issues/83

I think the ARS output (that the ARAX GUI uses) should be able to communicate the difference between a timeout (no answer), a 500 level server error vs a 400 level error (specifically one that says "the query is fine, but I don't support it") as Greg describes above.

I think it would be good to get some time with the ARS team to design how their output could be enhanced so that the UI can better describe what happened.

_Originally posted by @edeutsch in https://github.com/NCATSTranslator/testing/issues/91#issuecomment-888763989_

**Comment by MarkDWilliams** [comment]
I added an update on that ticket, but it looks like we are already returning the status code, but it's not within the TRAPI portion of the response (everything under `message`).

**Comment by MarkDWilliams** [comment]
This should have been fixed here
https://github.com/NCATSTranslator/Relay/pull/187/files
