### ISSUE TITLE
ARAX TRAPI 1.2

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/Relay#202]
Hi, the ARAX TRAPI 1.2 endpoint is up. You can find it in SmartAPI:
https://smart-api.info/registry?q=rtx

Specifically:
https://smart-api.info/ui/e3bebc6620243bd978a6b92d39c0318d

There's also an "RTX KG2" KP endpoint that you may wish to add to the "KP" list:
https://smart-api.info/ui/acca268be3645a24556b81cc15ce0e9a
(or not if not appropriate)

**Comment by edeutsch** [comment]
Specifically, this endpoint:
https://arax.ncats.io/api/arax/v1.2/asyncquery
is ready for your testing. Let us know how it goes.

**Comment by MarkDWilliams** [comment]
The dev instance has been updated with the async endpoint.

**Comment by edeutsch** [comment]
Great, thanks! I tried to submit a query to
https://ars-dev.transltr.io/ars/api/submit
and it seemed to work!
The last log messages I see at ARAX from that ARS-initiated query is:
```
2021-09-08T21:32:58.570847 INFO: [] Attempting to send to callback URL: https://ars-dev.transltr.io/ars/api/messages/a098ce14-8fac-4c39-9f7a-0b1d7e974c06
2021-09-08T21:32:59.772429 INFO: [] Response from POST to callback URL was 201
```

But I'm not able to see that that result when viewing the results here:
https://arax.ncats.io/?source=ARS&id=5eba5040-4e9b-4cde-af55-4c9f32ac8204

oh wait, yes, now it does show up! It seemed like there was a long delay in the time between I expected to see our result at ARS and the time when it did actually work.

Maybe still some refinement needed, but it does seem to work at some level.

**Comment by edeutsch** [comment]
I did one more test, and it seems to be working fine now. There's no visible result on the first load. But upon reloading the ARS result page a little while later, the ARAX result was there, so everything seems in order and working with /asyncquery.

**Comment by edeutsch** [comment]
Although it was working yesterday, today when I try this again, I am seeing this on the ARAX side:
```
2021-09-09T15:42:15.696399 INFO: [] Processing is complete. Attempting to the result to the callback URL.
2021-09-09T15:42:15.696423 INFO: [] Attempting to send to callback URL: https://ars-dev.transltr.io/ars/api/messages/57aa3d3f-7f34-4600-9c76-7522c3964fee
2021-09-09T15:42:18.025263 INFO: [] Response from POST to callback URL was 413
```
Yesterday we got a 201, but today we get a 413.
413 appears to be a payload too large error.
Our payloads vary in size depending on which KPs respond. 
I'm guessing that yesterday BTE did not answer before we gave up and so the answer was smaller and ars-dev accepted it. But maybe today BTE answered and so our answer is much larger and the payload was rejected.

I recall needing to adjust the nginx max payload size on our server. Maybe you need to update ars-dev nginx to accept larger payloads?

**Comment by edeutsch** [comment]
When I test workflow3.json for tomorrow's standup call at ars-dev, ARAX gets a 413 when it tries to post the result to the callback URL. 413 is payload too large.

**Comment by MarkDWilliams** [comment]
ARS has been updated with ARAX 1.2 and async.  The 413 issue has been resolved
