### ISSUE TITLE
ARAGORN with TRAPI 1.2 support is available for testing.

### ISSUE THREAD

**Issue by PhillipsOwen** [NCATSTranslator/Relay#203]
The TRAPI 1.2 compliant ARAGORN component is in smart-api at:
 - https://smart-api.info/registry?q=86c92eba3d7b85720db2501fa32d6cdd

The ARAGORN endpoints are: 
 - https://aragorn.renci.org/1.2/asyncquery
 - https://aragorn.renci.org/1.2/query

**Comment by MarkDWilliams** [comment]
The dev instance has been updated with the async query endpoint.

**Comment by MarkDWilliams** [comment]
prod/ci have been updated with the 1.2 endpoints
