### ISSUE TITLE
Clinical Services KPs TRAPI 1.2

### ISSUE THREAD

**Issue by CaseyTa** [NCATSTranslator/Relay#206]
OpenPredict: https://smart-api.info/ui/e9f69b81e755e163fdf6c41a2b5e07c0
COHD: https://smart-api.info/ui/51c178099fa2dc99b5d8fff8bf9f1a0d

If we change the server URL in the Smart-API registry, will that automatically get picked up in ARS?

**Comment by MarkDWilliams** [comment]
Casey, unfortunately the ARS will no automatically update based on changes to smartAPI, but if you let me know when URLs change, I can change them on our end.

**Comment by MarkDWilliams** [comment]
This has been added to the ARS, but let me know if you change the URL

**Comment by CaseyTa** [comment]
Hi Mark, we just turned off TRAPI 1.1 today and put TRAPI 1.2 working on the main https://cohd.io/api/. The above SmartAPI registration has been updated accordingly.

I'll leave trapi-dev.cohd.io/api/ up and running I hear confirmation from you that ARS has been updated. Thanks!

**Comment by MarkDWilliams** [comment]
Am I reading the SmartAPI correctly that openpredict's URL did not change?  I have updated the registration for COHD

**Comment by CaseyTa** [comment]
@MarkDWilliams, correct, thanks!
