### ISSUE TITLE
Update CODEOWNERS

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#222]
Master pull requests behavior keys off entries in CODEOWNERS, which needs updating

https://github.com/NCATSTranslator/Relay/blob/master/CODEOWNERS

**Comment by MarkDWilliams** [comment]
So, what's the plan for this?  Make me the only code owner?  If we do that, do we know if I would get caught in a catch22 of not being able to approve my own PRs but not having another code owner to do so?  Can we change the behavior to allow me to approve my own PRs?

**Comment by southalln** [comment]
Updated
