### ISSUE TITLE
Update and add ICEES instances

### ISSUE THREAD

**Issue by maximusunc** [NCATSTranslator/Relay#237]
Hello, we'd like to update the two existing ICEES urls:
- `icees` should now be `icees-asthma`
  - the smartapi url is: https://smart-api.info/ui/bb806f5c81e86fe12660fa307d4b0a97
  - You can POST to: https://icees-asthma.renci.org/query
- `icees-dili`
  - the smartapi url is: https://smart-api.info/ui/749c8f527fa07964de692e0969b71a4e
  - You can POST to: https://icees-dili.renci.org/query

We would like to add a new ICEES instance:
- `icees-pcd`
  - the smartapi url is: https://smart-api.info/ui/4153c947a32e2e2a55a320d0bee22077
  - You can POST to: https://icees-pcd.renci.org/query

Thank you!

**Comment by MarkDWilliams** [comment]
This has been added in our test environment, but there are some unrelate database issues that we need to work out on that environment.  I'll let you know as soon as we get that resolved and pushed to production

**Comment by maximusunc** [comment]
Thanks @MarkDWilliams. Taking a look at #239, it looks like PCD was added, but the other two icees instances are still using the old urls. Could you update those as well please?

**Comment by sstemann** [comment]
@MarkDWilliams did you make these updates?

**Comment by karafecho** [comment]
Also, to clarify Max's post, in addition to updating the URLs and adding a new `icees-pcd` instance, we would like to rename the ICEES Asthma instance as `icees-asthma` (not `icees`). Thanks!

**Comment by karafecho** [comment]
@MarkDWilliams : I thought I'd check on the status of this ticket. 

Just so you are aware, I've been testing a number of Clinical Data Committee get_creative() queries that should invoke `icees-pcd` but do not due to the registration issues. I'm hoping we can resolve the issue sometime soon. Thanks!

**Comment by karafecho** [comment]
@MarkDWilliams : Not sure if this ticket should be reopened or not (feel free to close it if the latter), but I just posted the following message to Translator # general and figured I should alert you.

_I wanted to alert folks to a few changes to ICEES. Specifically, shortly before the September relay, we deployed a new service, icees-kg, to the ITRB production environment. (I had announced this, but I think my message was lost in pre-relay preparations. :slightly_smiling_face:) icees-kg provides a graphical representation of four ICEES datasets, asthma, PCD, DILI, and COVID, each containing one or more years of integrated patient + exposures data. icees-kg is intended to replace icees-asthma, icees-pcd, and icees-dili as the sole ICEES-related Translator KP. The fully featured icees-asthma, icees-pcd, icees-dili, and icees-covid services remain available, just not as Translator services._

_Note that icees-kg should represent an improvement in our previous approach in that: (1) it provisions new data on COVID; (2) response time should be super quick and reliable; and (3) it is fully compliant with all regulatory and institutional restrictions for ITRB cloud deployment._

_Please feel free to reach out to me, should you have questions._

_Thanks!_

![image](https://user-images.githubusercontent.com/26254388/210891173-16f4b21a-fe01-447c-9803-ff1436bcec6e.png)

**Comment by MarkDWilliams** [comment]
@karafecho Is the new icees-kg meant to replace the existing instances or would you like it added to the ARS in addition to DILI, etc?

**Comment by karafecho** [comment]
Thanks for checking, Mark. icees-kg is intended to replace the three other ICEES instances, namely, icees (asthma), icees-pcd, and icees-dili.

**Comment by MarkDWilliams** [comment]
Apologies for the delay, Shervin and I are working on this and hope to have the new instance in with next week's batch of ITRB change approvals.

**Comment by karafecho** [comment]
Thanks, Mark!

**Comment by sstemann** [comment]
deployed to prod
