### ISSUE TITLE
Align Response Inheritance between Workflow Queries and Non-Workflow

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#251]
Currently, responses to queries without workflow instructions are presented as all being children of the ars-default-agent, whereas responses to queries that do have workflow are presented as children of the workflow-agent.  This causes issues with the ARAX interface's ability to pull results from the ARS as it does so by looking for the specific PK of the default agent.

**Comment by edeutsch** [comment]
These parts of the ARAX GUI were developed on empirical observations on how the ARS seemed to behave, and it's been tricky with the various versions of ARS all behaving a bit differently. If there is a specification we should be following, just point us at it. But otherwise I need some repro examples that I can examine and adjust the code to handle.

Basically, I need to be able to distinguish between a "parent" pk and a "child" pk. Here's the current code:
```
                if 'name' in response_dict['fields'] and response_dict['fields']['name'] != '':
                    if response_dict['fields']['name'] == 'ars-default-agent':
                        is_parent_pk = True
                    else:
                        is_parent_pk = False
                elif 'actor' in response_dict['fields'] and ( str(response_dict['fields']['actor']) == '9' or str(response_dict['fields']['actor']) == '19' ):
                    is_parent_pk = True
```

What needs to change?

**Comment by ShervinAbd92** [comment]
@edeutsch, So since we have added a field name, can we just distinguish the parent vs child with the name field? Would something like this work?
```
      if 'name' in response_dict['fields'] and response_dict['fields']['name'] != '':
             if response_dict['fields']['name'] == 'ars-default-agent' or response_dict['fields']['name'] == 'ars-workflow-agent':
                   is_parent_pk = True
             else:
                   is_parent_pk = False
```

**Comment by MarkDWilliams** [comment]
And thanks for looking into this issue Eric.  I wish we had a proper spec sheet for you, but I appreciate you working with us on this and other ARS issues.

**Comment by edeutsch** [comment]
@ShervinAbd92 I can change the code to what you suggest if you agree. I have not seen any data to know if this would work.

**Comment by edeutsch** [comment]
@ShervinAbd92 I just deployed your suggested fix to https://arax.ncats.io/test/
I have no way to test. Can you test?

**Comment by ShervinAbd92** [comment]
@edeutsch I did send a workflow query and it works now! thank you :)

**Comment by edeutsch** [comment]
okay, I will commit this change and start distributing it through all the various instances. It may not show up in production until Wednesday or so.
