### ISSUE TITLE
Enable differentiation between parent and child PKs

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#261]
In order to allow ARAX interface to pull results from different ARS deployments, a method to differentiate parent and child PKs is needed.  Some examples are below:
Root pk: https://ars.ci.transltr.io/ars/api/messages/abfb2364-4a66-4762-9dc6-944c04ba9c65?trace=y
Aragorn specifically: https://ars.ci.transltr.io/ars/api/messages/296c901b-7c9a-42c6-a8d8-c5e7874ea305

**Comment by edeutsch** [comment]
okay, after more testing, it seems that the 19 still sometimes gets me into trouble. Changed to do this:

if name exists and name is not empty, then if name == "ars-default-agent" then it's a parent
if name does not exist (like it still is in production?) or is blank, then fall back to the previous actor code, which is assuming that actor 9 is ARS.

I hope that will do it.
I will commit that.
Let me know if you have concerns

**Comment by edeutsch** [comment]
I have implemented this and rolled it out everywhere. and tested a little. Please test more and let me know if I got this right.

**Comment by edeutsch** [comment]
Luis and I worked on one more fix last night that I haven't pushed around yet, so maybe hold off until I can push that out to all endpoints later today..

**Comment by edeutsch** [comment]
@MarkDWilliams I have now rolled out our latest code everywhere. Please try it now and let us know how it works

**Comment by MarkDWilliams** [comment]
@edeutsch Everything seems to be in working order.  Thanks for your help on this.  I'll get the ARS changes pushed out to production.
