### ISSUE TITLE
Develop new database for long term storage

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#266]
In order to keep data retention sensible going forward at larger scale, I propose making a new database to house results that need to be retained.

- A new endpoint will be needed to mark a message for retention
- Messages not marked for retention will be deleted after 30 days
- Communication will need to occur with the UI team to add a button to mark a result for retention.
- Unsure if software for the new database should be stand alone or folded into the existing ARS code.

**Comment by sstemann** [comment]
ask ITRB on 3/8
