### ISSUE TITLE
Report Card Endpoint for Registered Tools

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#301]
Requested on 09/27/2022 Architecture call, an ARS endpoint to give the following information regarding a tool's daily performance:

1. List of PKs/queries submitted to that tool (in the last 24 hours?)
2. Status code of those queries (as the ARS knows it)

Nice to have but not necessarily a requirement for the initial version:

1. Number of results returned for each PK 
     a.  This will require a pre-counting/caching of the number of results on receipt of them by the ARS.  Otherwise, we have to fetch the whole thing just to count them.
2. Time this took
     a.  This will likely require an update to the Message object to track this from start to finish and a fair amount of testing.

**Comment by MarkDWilliams** [comment]
This is implemented, but requires optimization.  Works in lower-traffic environments, but struggles to pull back the number of records that span a 24 hour period in prod.  Reduce the timeframe?  Optimize the query?

**Comment by ShervinAbd92** [comment]
modified the code to only fetch the fields that we would need from message object (i.e code, id, timestamp, updated_at, result_count). Submitted PR #323

**Comment by sstemann** [comment]
deployed to prod
