### ISSUE TITLE
Asynchronous Timeout Functionality

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#321]
While we wait for ARAs to implement a URL at which we can check the status of async queries and mark them as timed out or in error based on that, we are implementing a flat timeout queue for async queries wherein, after 10? 15? minutes, they will just be marked as 598.

**Comment by sstemann** [comment]
Submitted CRs 1/6 for CAB review 1/20
- Dev/CI[CHG0031321](https://support.ncats.nih.gov/nav_to.do?uri=change_request.do%3Fsys_id=2688f9601bd8a950321484cae54bcbf0%26sysparm_stack=change_request_list.do%3Fsysparm_query=active=true)
- Test [CHG0031322](https://support.ncats.nih.gov/nav_to.do?uri=change_request.do%3Fsys_id=1f2db5241bd8a950321484cae54bcb9b%26sysparm_stack=change_request_list.do%3Fsysparm_query=active=true)
- Prod [CHG0031323](https://support.ncats.nih.gov/nav_to.do?uri=change_request.do%3Fsys_id=1b8d7da41bd8a950321484cae54bcb0b%26sysparm_stack=change_request_list.do%3Fsysparm_query=active=true)

**Comment by sstemann** [comment]
related to https://github.com/NCATSTranslator/TranslatorArchitecture/issues/83

**Comment by sstemann** [comment]
Approved.  Pushed to CI 1/20. Pushed to Test 1/23.

**Comment by sstemann** [comment]
Need to coordinate on:
- manual database change - could take up to four hours to run causing an ARS outage

**Comment by sstemann** [comment]
deployed to prod in 1/31 build
