### ISSUE TITLE
Initial Filter Implementation - # hops, node type, specific node, normalized score

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#322]
Working on filters to be implemented for use by UI and others in the consortium.  These would include node types, specific node, confidence level, number of hops, etc.  My plan for this would be a single "filters" endpoint which could receive a list of specified filters and their parameters as well as a PK on which to perform these things.  Then, a new PK would be generated which contains the filtered/altered results and that PK (or perhaps the whole JSON?) would be sent back.

Confirming the initial implement is in progress to include node type, specific node (per 1/17 standup).

**Comment by MarkDWilliams** [comment]
Need to double check the current level of implementation of these filters currently @ShervinAbd92  and touch-base with O&O about which filters are needed and the details of their implementation

**Comment by sstemann** [comment]
This is what we discussed was left to do as of 1/6 - @ShervinAbd92 could you document which filters are currently done and which will be included in this release?

**Comment by ShervinAbd92** [comment]
Hi Sarah, I believe that so far we have worked on Number of hops and
confidence level. I will be working on Node type and specific node while
Mark is out.

**Comment by ShervinAbd92** [comment]
Hi Sarah, i have implemented 4 filters (node types, specific node, score level, number of hops) into ARS and pushed the branch "User_filter" on the Relay repo. As of now it doesn't support filtering in combination but we can definitely implement that in future.

**Comment by sstemann** [comment]
@ShervinAbd92 to try adding a list of available filters and their parameters

**Comment by sstemann** [comment]
Deployed to prod in 1/31 build

https://ars-prod.transltr.io/ars/api/filters/?
