### ISSUE TITLE
Next set of filters - Novelty, Recency

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#325]
O&O Proposes that ARS implement filters for:

- Novelty - see comment "three kinds of novelty" below 
- Recency

Pending:
- #322 - includes - Node type (by NamedThing), specific node ids, Hop count, Confidence level

- More detailed requirements on recency
- Confirmation on what attributes to use for "novelty"

**Comment by sstemann** [comment]
For novelty - I believe we are actually waiting for TRAPI to log a PR for extra info to include asserted, predicted attributes on the edges.  Per the 1/5 [TRAPI call, ](https://docs.google.com/document/d/16dV4WI_5L6nFzKzXLsCRXeLcjcCZ3MtxvP1JqKgFY-E/edit?usp=sharing) where the "Extra Info ..." proposal from Matt was reviewed, the next step is for them to create a draft - ARS can't implement for this edge attribute until the change is implemented in TRAPI, then the ARAs/KPs.  That timeline would be with TRAPI

For recency - at the liaisons call, it sounded like Christine also had thoughts here, have the specifics of the date attributes and logic been discussed at O&O WG meeting?  are those details somewhere we can take a look?

**Comment by sharatisrani** [comment]
Recency of a path result == most recent date of any edge.
No date on edge implies "not recent"
See last bullet on: https://docs.google.com/presentation/d/1-hQGMi5DhG3y_CcTNnNCBr95yVRdyL0f/edit#slide=id.p36
We need to "ratify" this within ARS and in some settings (which all - ARA? EPC? TRAPI?)

**Comment by sharatisrani** [comment]
There are three kinds of Novelty:

1. (for any edge or path result) Predicted/Inferred
2. (for literature sources) Recency.  See above.
3. (for clinical sources) Evidence beyond FDA approvals.  We await TCDC's study of their "Option 2"

**Comment by MarkDWilliams** [comment]
This faceting is now handled in the UI
