### ISSUE TITLE
Incorporate how ARAs calculate score during Normalized Score Calculation

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#333]
ARS Score Normalization should consider taking into account the specific methods of how ARAs calculate scores.  

First steps: Tyler to reach out to ARAs regarding documentation (hopefully some of this is available programmatically)

related to #325 (Confidence Levels)

**Comment by sstemann** [comment]
Two ARAs responded
- ARAGORN
- Explanatory (xARA) - 13 different algorithms, depends on the question

Tyler to follow up with David K. (ARAX)

**Comment by MarkDWilliams** [comment]
I'm not sure if this is compatible with the other scoring efforts happening.
