### ISSUE TITLE
Incorporate Upper and Lower Bounds for Scoring

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#356]
Pending ARAs from Tyler's Feb 2023 Relay Request

**Comment by sstemann** [comment]
will be added to Arch Committee Progress Tracker 3/7

Requirements:
- No specific range 
- Must have min/max 
- Must be positive
- Higher has to be better

**Comment by sstemann** [comment]
Specific range is 0 to 1

ARAX, BTE, and ARAGORN are compliant.

@MarkDWilliams  Need to check on Unsecret and Improving

**Comment by MarkDWilliams** [comment]
I believe this is complete and should be overcome by F() and G() scores
