### ISSUE TITLE
Additional changes needed during normalization process

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#363]
Ref: https://github.com/NCATSTranslator/Feedback/issues/134
During the course of changing nodes in `results` and `knowledge_graph` as part of the node normalization process, we neglected to apply these same changes to `subject` and `object` fields on edges.  These changes should be extended to include the CURIEs which exist as values for `subject` and `object` on KG edges as well.

**Comment by cbizon** [comment]
FWIW, there is a (badly-named) endpoint on NN `/response` that normalizes an entire TRAPi response.  It normalizes the nodes as well as the edges, and it supposedly handles the case where e.g. two nodes on the input KG normalize into a single node on output.   I say supposedly b/c I don't think it has ever gotten used widely, but you may find it useful either from calling or from looking at its implmentation.

**Comment by MarkDWilliams** [comment]
Good looking out.  I did not recall that and will look into it.
