### ISSUE TITLE
Investigate Use of Node Normalizer Whole Response

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#364]
Chris B informs me that there is an endpoint in the node normalizer to normalize an entire TRAPI Message (kg, results, etc) as opposed to the piecemeal way we currently have implemented.  We should look into using this method as normalizing the entire message is what we're ultimately doing.

**Comment by sstemann** [comment]
will address #363 first

**Comment by ShervinAbd92** [comment]
taking a look at SRI node normalizer code gave us the idea of incorporating equivalent_identifiers and type fields that normalizer returns into our nodes. As for equivalent_identifiers we will only add the "same_as" attribute only if it doesn't already exists in the attribute list. However, as for type field we are not certain that adding it to the node categories field is a good idea as it includes most of connecting entities to our queried entity.
