### ISSUE TITLE
Make SQL Script for Scoring Test Data

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#371]
David K and the folks on the scoring call have requested a dump of data from the ARS which contains full json responses sent by ARAs to MVP Queries.  We can approximate this by selecting from the Messages table entries which have in their query_graph an "inferred" edge.  This will still include some things not sent by the UI and likely some malformed or unusual queries, but lacking a sender_id, we can't tell from the database which entries were actually sent by the UI.  The output of this script should be a SQL dump of data from the Messages table, and include the full json response if one was sent.

**Comment by sstemann** [comment]
provided to scoring subgroup on 3/14
