### ISSUE TITLE
Add timestamp to data returned from `/reports` endpoint

### ISSUE THREAD

**Issue by maximusunc** [NCATSTranslator/Relay#383]
Hitting the `/ars/api/reports/{actor}` endpoint currently returns a list of pks containing their status_code, time_elapsed, and result_count. Is it possible to also include a timestamp?

@cbizon

**Comment by MarkDWilliams** [comment]
Sure, I think we should have pretty easy access to a timestamp for when that query was created (effectively when it was sent to the ARA) and when it was last updated.  Which of these would be most useful to you? Or both.

**Comment by maximusunc** [comment]
I think the more information, the merrier!

**Comment by ShervinAbd92** [comment]
Hi @maximusunc, we have added those times (start and updated) to the report endpoint in the CI environment. please give it a try :)

**Comment by maximusunc** [comment]
Looks good! I've already updated the query logger tool to display these. Thanks!
