### ISSUE TITLE
catch_timeout not catching timeouts in cases of error

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#387]
There are instances of async results failing with an error when they are returned.  Despite more than one hour having passed with no results, they are not being marked as 598.  In these cases, the correct behavior should be to update the Message with an error code upon error (see: https://github.com/NCATSTranslator/Relay/issues/386) but the fact remains that this shows some failure in our current attempts to catch timeouts.

**Comment by MarkDWilliams** [comment]
I believe this issue is resolved. @ShervinAbd92 ?

**Comment by ShervinAbd92** [comment]
Yes @MarkDWilliams, Its been resolved
