### ISSUE TITLE
Add a message to reflect when ARS System Components are not working to the ARS Status Page

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#40]
There are various scenarios where the ARS could malfunction (Celery down, etc) that need to give a message on the Status Page (https://ars.transltr.io/ars/app/status).  Currently it looks like the actors/agents aren't working - which isn't a true reflection of the status

**Comment by southalln** [comment]
I'm not sure I have a great way to detect that Celery isn't working, but I've added a message to the status page (currently in dev) when none of the children of the last submitted query have a status other than error and unknown - which looks like a good surrogate for this state.
https://github.com/NCATSTranslator/Relay/commit/4aeafaf509a1ba92e37bf156f62ff242b3a3ee10#r42381626

**Comment by sstemann** [comment]
working as expected
