### ISSUE TITLE
Update Merging Code

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#414]
Merging code needs to be updated and tested against 1.4.  It should be invoked in the following way

1. ARS receives the second response to a query (B)
2. The second response is merged with the first, creating a new Message (AB)
3. With each subsequent response, a new merge is initiated on the most recent ARA response with the most recent merged set
A, A+B=AB, AB+C=ABC, ABC+D = ABCD, etc

Things to consider:

- Do we want to merge edges?
- Are we preserving the inforesids of each ARA that contributed to a given node, edge, result, etc?  This is allegedly a non-issue with EPC belonging to the analyses objects in 1.4, but we should check anyway.
- The invocation of the merge code should be changed to be automatic as opposed to being invoked manually by hitting the endpoint (we can leave the manual method for testing purposes though)
- Should merging drop log objects from constituent Messages?  Does a mixed set of logs make any sense/have any value?
- We will need some way to notify the UI that a merge has happened.  We will either need to save merged things to the same PK (and then save the previous elsewhere?) or add some field which contains the PK of the next merged Message in the chain.

**Comment by sstemann** [comment]
1.4 Updates Completed, Updating Behavior, @MarkDWilliams to discuss with Gus (UI) 

Planning to modify the message model to include Merge From and Merge To (PKs to trace), and Lock to deal with age condition

**Comment by MarkDWilliams** [comment]
Done
