### ISSUE TITLE
Add code to invoke clinical service

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#415]
The ARS will need to call out to the clinical service with each new response received.  This call should happen in the same place that the node normalizer is called and should be wrapped with error handling.  In the event of an error, the status of the Message should be set to 206, a descriptive error should be output to the ARS log, and a new `log` object should be added to the Message.  

This ticket depends on the implementation of the clinical service

**Comment by sstemann** [comment]
@MarkDWilliams to discuss with Kara and Rosina re: design of O&O Clinical Evidence f-score factor implementation:

https://docs.google.com/presentation/d/1YWCxJGpwyXS2pM00CkJsOBfobDZmr29A/edit?usp=sharing&ouid=105746645933190529944&rtpof=true&sd=true

**Comment by sstemann** [comment]
Kara is compiling documentation for how it interfaces with f and g scores and how it will be invoked by the ARS. 

Core: this will be a service that the ARS will call and add annotations from the service (scores of clinical evidence goodness) to the nodes/edges.

If UI/UX says yes we have clinical evidence but the edges don't show it, then we need a way to add an edge (artificial) to describe the clinical evidence that exists.  This will happen on the clinical service side, (not on the ARS, bc the ARS does not add). 

Options:
- tack on to answer node 
- Edge added

**Comment by MarkDWilliams** [comment]
This is done
