### ISSUE TITLE
Add code to invoke annotation service

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#418]
The ARS will need to call out to the annotation service with each new response received. This call should happen in the same place that the node normalizer is called and should be wrapped with error handling. In the event of an error, the status of the Message should be set to 206, a descriptive error should be output to the ARS log, and a new log object should be added to the Message.

This ticket depends on the implementation of the annotation service.

**Comment by sstemann** [comment]
@MarkDWilliams to talk to Chunlei then we'll figure out when to do this.  plans to use a batch version.

**Comment by sstemann** [comment]
Chunlei sent over example queries, confirmed it supports bath queries.  It's up but not in SmartAPI.  

Will follow up to determine when service will be available in SmartAPI

**Comment by MarkDWilliams** [comment]
This should address this
https://github.com/NCATSTranslator/Relay/pull/430
