### ISSUE TITLE
Provide callback for message updates following initial creation

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#42]
Currently, ARS service agent/actors POST queries to resources synchronously and holds that connection open as long as is needed for the service action to be performed. The preferred behavior would be to provide a callback for services to POST responses and updates directly to the ARS, with the agent/actor service just replying with an initial status of 'in progress' or something.

**Comment by southalln** [comment]
See proposed standard update to accomplish this
https://github.com/NCATSTranslator/ReasonerAPI/pull/150/files/4e4f4e2cb5e5aaba400428ae556fcdf96080554b

**Comment by southalln** [comment]
This is partially addressed in:
https://github.com/NCATSTranslator/Relay/commit/9e1056e7a2dcfddd73a033cfd595a4866eec3f8f#r42393766

**Comment by southalln** [comment]
Other half here https://github.com/NCATSTranslator/Relay/commit/3472cddd82645dc81cfdae2d2f81d87562a8ee3a#r42395356

**Comment by edeutsch** [comment]
Would the ARS specify how often it wanted updates?
If a callback parameter were provided, would the ARS like one POST to the callback when the query is done?
or would it like POSTs to the callback every minute with partial information?
And then one final POST to the callback when the processing is done?
Would the partial-information posts be expected to be fully formed? with ranked results and all?
Our system is not really designed to provide "checkpoints" of results that are fully formed.
In fact, our system has a tendancy to create huge temporary knowledge graphs along the way, and the pare them down as the scoring and ranking completes. So an "in progress" knowledge_graph might be HUGE with no results[] yet computed. Is that helpful?
Or the partial POSTs could just be logs[] information about how the processing is progressing without the incomplete knowledge_graph currently being processed.

What do you think?

**Comment by southalln** [comment]
ARS isn't ready to specify a preferred behavior, yet. The callback can be used as often as desired right now. Most services are providing simple responses back within 10 sec, but we already have some queries that take 10 minutes to run. Give such a wide range of performance, we should probably discuss options like asking for an estimate ...

I particularly appreciate that interim responses might be quite a bit bigger than 'final' ones. Again, as long as network traffic is not limiting server behavior, the ARS will just accommodate whatever is sent for now.

**Comment by sstemann** [comment]
https://github.com/NCATSTranslator/ReasonerAPI/pull/150 - TRAPI v1.1
