### ISSUE TITLE
cam:kp unexpectedly still in ARS

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/Relay#425]
This issue ended up in the ARAX repo issues list, but if I understand it correctly, this is an ARS issue. ARS seems to be calling and listing cam-kp probably because it is hard coded in a list somewhere rather than fully dynamic?

See:
https://github.com/RTXteam/RTX/issues/2050

**Comment by edeutsch** [comment]
From @gaurav 

 Hi there! We've been working on moving CAM-KP into Automat. As part of that process, we have deleted every TRAPI 1.3 CAM-KP instance from SmartAPI and instead registered an Automat-CAM-KP instance. All of these are correctly visible in https://arax.ncats.io/?smartapi=1, where we see:

[Automat-cam-kp(Trapi v1.4.0)](https://smart-api.info/ui/fb71332c85d38539ba64ae148a6e3df7) (infores:automat-cam-kp) in staging, testing and development.
[CAM-KP API](https://smart-api.info/ui/642b1dbcd0943f3a119d714cf7535fba) (infores:cam-kp) on TRAPI 1.3 in development
On running a [recent query through the UI](https://arax.ncats.io/?r=85dd37b4-1b80-4ec9-8f1b-a9b423d59980), I noticed that agent kp-cam returned a 404 error. However, all of the CAM-KP instances mentioned above should be working. Is there some other place where we should change the reference from kp-cam to automat-cam-kp so that ARAX can retrieve results from it correctly?

**Comment by edeutsch** [comment]
(ARAX is just displaying what ARS provides, so I think this is an ARS issue)

**Comment by ShervinAbd92** [comment]
hi @edeutsch we have updated ARS reference on automat-camp-kp. it should now point to 1.4 CI url. i just ran a quick query and i did get a 200. can you please test it out on your query and let us know if the issue is fixed?

**Comment by edeutsch** [comment]
Looks good thanks!

As a side note, I am wondering if it is worth reviewing all the targets that ARS hits? The list of KPs would seem to be only a partial list. And at the Relay, there seemed to be confusion if we should even be calling Robokop, and I think it was said that Robokop was a KP for Aragorn, not an ARA? And should the ARS even be calling KPs directly anymore? or is it time to limit the ARS just to the main ARAs? I don't the  answers to these, but I'm wondering if a fresh look at this is warranted. Bring up at Architecture next week?

**Comment by MarkDWilliams** [comment]
Sure, I think this would be worth reviewing in Architecture, and changing what the ARS hits is a pretty simple task.  The design aim was certainly not to hit the KPs forever, and it may be time to take a fresh look at whether now is the time to make that cut.
