### ISSUE TITLE
Disease Merge Issues

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#471]
On the Data Modeling Testing Thursday - Gwenlyn identified substances in MVP1 that were not normalized

https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=1fe9cae2-1531-44c9-9053-6fdb52b500e3

methotrexate
- Unsecret:  DRUGBANK:DB00563
- BTE: PUBCHEM.COMPOUND:126941R
- ROBOKOP: PUBCHEM.COMPOUND:126941
 
(-)-Epigallocatechin gallate
- Unsecret: DRUGBANK:DB12116
- BTE:  PUBCHEM.COMPOUND:65064

Ustekinumab
- Unsecret: DRUGBANK:DB05679
- BTE:  MESH:D000069549
- ROBOKOP:  MESH:D000069549

Tretinoin
- BTE:  PUBCHEM.COMPOUND:444795
- BTE:  UMLS:C0040845

Retinol
- BTE:  PUBCHEM.COMPOUND:445354
- ROBOKOP:  PUBCHEM.COMPOUND:445354
- Unsecret:  DRUGBANK:DB00162

**Comment by MarkDWilliams** [comment]
I believe I have found the problem.  It is a bug I introduced when I changed the saving behavior for ARA original responses to improve performance.  I should be able to have a fix out shortly

**Comment by MarkDWilliams** [comment]
Confirmed fixed in CI.  The only place DRUGBANK:DB00563 shows up in Unsecret's response to the first query now is in the paper trail attribute that the ARS adds when it changes a node via normalization
https://ars.ci.transltr.io/ars/api/messages/90236545-c7cf-42ed-b492-d3971f20874d?trace=y
https://ars.ci.transltr.io/ars/api/messages/f37f15f0-c9f5-4569-a485-7a690b43a290
```"PUBCHEM.COMPOUND:126941": {
              "name": "Methotrexate",
              "attributes": [
                {
                  "value": [
                    "DRUGBANK:DB00563"
                  ],
                  "value_url": null,
                  "description": null,
                  "value_type_id": "metatype:NodeIdentifier",
                  "attribute_source": null,
                  "attribute_type_id": "biolink:xref",
                  "original_attribute_name": "original_id"
                },
                {
                  "value": [
                    "PUBCHEM.COMPOUND:126941",
                    "CHEMBL.COMPOUND:CHEMBL34259",
                    "UNII:YL5FZ2Y5U1",
                    "CHEBI:44185",
                    "DRUGBANK:DB00563",
                    "MESH:D008727",
                    "CAS:102613-64-9",
                    "CAS:59-05-2",
                    "DrugCentral:1751",
                    "HMDB:HMDB0014703",
                    "KEGG.COMPOUND:C01937",
                    "INCHIKEY:FBOZXECLQNJBKD-ZDUSSCGKSA-N",
                    "UMLS:C0025677"
                  ],
                  ```
