### ISSUE TITLE
Update kp-icees-kg urlRemote

### ISSUE THREAD

**Issue by maximusunc** [NCATSTranslator/Relay#494]
Looking at this list: https://ars.ci.transltr.io/ars/api/actors the `urlRemote` for icees-kg is still pointing to the /1.3/ version. Could we please update this to /1.4/? That should fix all 405 errors coming from icees-kg.

@karafecho

**Comment by maximusunc** [comment]
Hi @MarkDWilliams @sstemann any chance this could become a priority? The CQS development kind of needs this fixed in order for ICEES-KG to be used. Thanks!

**Comment by karafecho** [comment]
Also see https://github.com/NCATSTranslator/Relay/issues/501.
