### ISSUE TITLE
Message status is "running" after connection timeout

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Relay#51]
Submitting this test query
https://slack-files.com/TSCGQ3XGB-F01ARUUBH8S-b59bab246b

Can take some time to execute. It appears that the connection times out before a response is received. 
One example response can be seen in this message thread:
https://ars.transltr.io/ars/api/messages/0925ff3c-7cb2-4b12-abd4-e4f22c10e3d2

Update status to unknown or error if connection is lost.

**Comment by sstemann** [comment]
message status should be updated to Error if the connection is broken

**Comment by MarkDWilliams** [comment]
This looks to be an issue independent of the timeouts that we set in tasks.py.  It seems that the threads are being killed by either django or celery and that that timeout is shorter than any of the ones we have set.
`HTTP POST /ara-ncats/api/runquery 500 [1.87, 127.0.0.1:35192]
/ara-bte/api/runquery: received payload...
b'{"model": "tr_ars.message", "pk": "43ad5daf-92cb-41bb-98e0-f5d15c87fb66", "fields": {"name": "", "code": 200, "status": "Running", "actor": {"id": 3, "channel": 1, "agent": 3, "uri": "http://localhost:8000/ara-bte/api/runquery"}, "timestamp": "2021-01-28T20:15:52.840Z", "data": {"message": {"query_graph": {"nodes": {"n00": {"id": "MONDO:0020310", "category": "biolink:Disease"}, "n01": {"category": "biolink:ChemicalSubstance"}}, "edges": {"e00": {"subject": "n00", "object": "n01"}}}}, "callback
Starting new HTTPS connection (1): api.bte.ncats.io:443
HTTP b'POST' request for ['127.0.0.1', 35220]
https://api.bte.ncats.io:443 "POST /v1/query HTTP/1.1" 200 None
200: {'Server': 'nginx', 'Date': 'Thu, 28 Jan 2021 20:15:59 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'X-DNS-Prefetch-Control': 'off', 'Expect-CT': 'max-age=0', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains, max-age=15768000', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'X-Permitted-Cross-Domain-Policies': 'none', 'Referrer-Policy': 'no-referrer', 'X-XSS-Protection': '0', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip'}
{"message":{"query_graph":{"nodes":{"n00":{"id":"MONDO:0020310","category":"biolink:Disease"},"n01":{"category":"biolink:ChemicalSubstance"}},"edges":{"e00":{"subject":"n00","object":"n01"}}},"knowledge_graph":{"nodes":{"MONDO:0020310":{"category":"biolink:Disease","name":"familial focal epilepsy with variable foci","attributes":[{"name":"equivalent_identifiers","value":{"id":{"label":"familial focal epilepsy with variable foci","identifier":"MONDO:0020310"},"db_ids":{"MONDO":["MONDO:0020310"],"
HTTP 200 response started for ['127.0.0.1', 35194]
HTTP close for ['127.0.0.1', 35194]
HTTP response complete for ['127.0.0.1', 35194]
HTTP POST /ara-bte/api/runquery 200 [6.59, 127.0.0.1:35194]
/ara-arax/api/runquery: received payload...
b'{"model": "tr_ars.message", "pk": "43ad5daf-92cb-41bb-98e0-f5d15c87fb66", "fields": {"name": "", "code": 200, "status": "Running", "actor": {"id": 2, "channel": 1, "agent": 2, "uri": "http://localhost:8000/ara-arax/api/runquery"}, "timestamp": "2021-01-28T20:15:52.840Z", "data": {"message": {"query_graph": {"nodes": {"n00": {"id": "MONDO:0020310", "category": "biolink:Disease"}, "n01": {"category": "biolink:ChemicalSubstance"}}, "edges": {"e00": {"subject": "n00", "object": "n01"}}}}, "callbac
Starting new HTTPS connection (1): arax.ncats.io:443
HTTP b'POST' request for ['127.0.0.1', 35226]
HTTP disconnect for ['127.0.0.1', 35196]
HTTP disconnect for ['127.0.0.1', 35198]
HTTP b'POST' request for ['127.0.0.1', 35230]
HTTP b'POST' request for ['127.0.0.1', 35232]
HTTP disconnect for ['127.0.0.1', 35200]
HTTP disconnect for ['127.0.0.1', 35202]
HTTP b'POST' request for ['127.0.0.1', 35234]
HTTP b'POST' request for ['127.0.0.1', 35236]
HTTP disconnect for ['127.0.0.1', 35204]
HTTP disconnect for ['127.0.0.1', 35206]
HTTP b'POST' request for ['127.0.0.1', 35238]
HTTP disconnect for ['127.0.0.1', 35208]
HTTP b'POST' request for ['127.0.0.1', 35240]
HTTP b'POST' request for ['127.0.0.1', 35242]
HTTP disconnect for ['127.0.0.1', 35216]
HTTP b'POST' request for ['127.0.0.1', 35244]
HTTP disconnect for ['127.0.0.1', 35220]
HTTP b'POST' request for ['127.0.0.1', 35246]
HTTP disconnect for ['127.0.0.1', 35226]
HTTP b'POST' request for ['127.0.0.1', 35248]
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe6fbe6ff18>()]>> for connection <WebRequest at 0x7fe6fbb2c208 method=POST uri=/ara-arax/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe7004f0ee8>()]>> for connection <WebRequest at 0x7fe7065961d0 method=POST uri=/ara-robokop/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe7004eaa98>()]>> for connection <WebRequest at 0x7fe70032eb38 method=POST uri=/kp-genetics/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe6fbe6fc48>()]>> for connection <WebRequest at 0x7fe700bbfeb8 method=POST uri=/ara-unsecret/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe6fbc61918>()]>> for connection <WebRequest at 0x7fe6fbe656a0 method=POST uri=/kp-molecular/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe6fbc61fd8>()]>> for connection <WebRequest at 0x7fe70014aa58 method=POST uri=/ara-improving/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe6fbc615e8>()]>> for connection <WebRequest at 0x7fe700bbf940 method=POST uri=/ara-explanatory/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe7004ea948>()]>> for connection <WebRequest at 0x7fe6fa5535f8 method=POST uri=/kp-cam/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe6fbe41bb8>()]>> for connection <WebRequest at 0x7fe7010acc18 method=POST uri=/kp-textmining/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.
Application instance <Task pending coro=<ProtocolTypeRouter.__call__() running at /home/ubuntu/.local/lib/python3.6/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe7004f0198>()]>> for connection <WebRequest at 0x7fe700395390 method=POST uri=/ara-aragorn/api/runquery clientproto=HTTP/1.1> took too long to shut down and was killed.`

**Comment by southalln** [comment]
Fixed and released to prod. Current timeout is 300 sec (5 minutes)
