### ISSUE TITLE
change Content-type header from text/html to application/json

### ISSUE THREAD

**Issue by andrewsu** [NCATSTranslator/Relay#57]
Minor suggestion... Currently API calls (e.g., https://ars.transltr.io/ars/api/messages/fc7414d4-1f64-48f6-a4be-0775a6486227) use `Content-Type: text/html` in the response header.  So that my browser plugin identifies it correctly as json for pretty formatting, would be nice if that were switched to `Content-type: application/json`.  

(A bit confused because it looks like it should already be set up that way in https://github.com/NCATSTranslator/Relay/blob/master/tr_sys/tr_ars/api.py#L78 ?)

**Comment by sstemann** [comment]
@MarkDWilliams verify if this is fixed
