### ISSUE TITLE
Support TRAPI 1.0

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#58]
https://github.com/NCATSTranslator/ReasonerAPI/releases/tag/v1.0.0-beta

Should be in place by 1/15 like the ARA and KP teams

**Comment by southalln** [comment]
Utilize https://github.com/TranslatorSRI/reasoner-converter to provide 0.9x support in the interim and/or update the test queries to the 1.0 format.

**Comment by sstemann** [comment]
completed
