### ISSUE TITLE
Documentation - How to Run a Query through the ARS

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#61]

**Comment by MarkDWilliams** [comment]
I have begun work on this here:
https://docs.google.com/document/d/1zU0ljQ_gNDziZVLXYpVCKJ4HT1nu5lywyVN4MlMLfU8/edit

**Comment by MarkDWilliams** [comment]
Do I need to go into a level of detail like "query graphs are made of nodes and edges.  This is what nodes and edges are.  This is what a graph is. etc"?
