### ISSUE TITLE
When scores are all 0, rank is always set to 2

### ISSUE THREAD

**Issue by maximusunc** [NCATSTranslator/Relay#623]
What is the purpose of `rank` in the ARS results, and how is it calculated? I would expect them all to either be unique or to be 1?

**Comment by MarkDWilliams** [comment]
There are some odd parts in how tie-breaking "pushes down" ranks on tie.  The behavior is all in [scoring.py](https://github.com/NCATSTranslator/Relay/blob/master/tr_sys/tr_ars/scoring.py), but that code was written by Rosina's team and just ported over to the ARS.  I'm open to changing how ties are handled.

**Comment by maximusunc** [comment]
Is `rank` used anywhere? UI? I was kind of assuming it was just the index of the result, but it sounds more complicated. Anyways, this came about because of the automated tests reports, so I made an issue there to not use `rank` in those reports: https://github.com/NCATSTranslator/ARS_Test_Runner/issues/30

**Comment by ShervinAbd92** [comment]
Gus just confirmed that UI team doesnt use the rank returned from ARS, they calculate rank on their end.
