### ISSUE TITLE
Prod - Common Cold is ars-ars-agent Error 422

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#640]
Prod:  https://ui.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=eabcec40-5a1b-4c68-b4c0-0096305dafbb

PK:  eabcec40-5a1b-4c68-b4c0-0096305dafbb

<img width="922" alt="image" src="https://github.com/NCATSTranslator/Relay/assets/38321826/972f4c10-2c74-4d8a-923f-d0c7738eebfe">

Test:  
https://ui.test.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=9aefda7f-5337-4710-8698-182b29e8c1a1

PK:  9aefda7f-5337-4710-8698-182b29e8c1a1

<img width="872" alt="image" src="https://github.com/NCATSTranslator/Relay/assets/38321826/0c3783b7-be70-4ba6-b535-4b873a0f1cf8">

**Comment by ShervinAbd92** [comment]
Hi @sstemann I ran the same query in Prod and was able to get responses back https://ui.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=c509eeb3-3c44-4bcd-b483-68d7db4a29c4
![Screen Shot 2024-07-19 at 9 38 39 AM](https://github.com/user-attachments/assets/0b603b04-da02-4002-84c8-1aea45168e6c)
