### ISSUE TITLE
ARAX Not Returning Results for UMLS Identifiers

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#66]
https://github.com/RTXteam/RTX/issues/1127

**Comment by saramsey** [comment]
Hi Mark, Amy Glen reports that RTX issue 1127 is fixed. If you could please test it out from your end at your convenience, and let us know if it works for you, we would appreciate it. Thanks, Steve

**Comment by MarkDWilliams** [comment]
Issue resolved on our end as well.  Thanks to all involved!
