### ISSUE TITLE
Several examples use curly quotes, which is not legal JSON

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/Relay#67]
In:
https://github.com/NCATSTranslator/Relay/wiki/Use-Cases

several of the JSON snippets use curly quotes, which is not valid JSON and makes it difficult to copy-paste and use/test.

Can all the examples be made valid JSON?

**Comment by MarkDWilliams** [comment]
I believe this issue is now resolved, but let me know if there are any other issues.

**Comment by edeutsch** [comment]
Looks good, many thanks!
