### ISSUE TITLE
Register Connections Hypothesis Provider

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#69]

**Comment by sstemann** [comment]
http://smart-api.info/registry?q=855adaa128ce5aa58a091d99e520d396

**Comment by MarkDWilliams** [comment]
When I try
`curl -X POST "http://chp.thayer.dartmouth.edu/query" -H  "accept: application/json" -H  "Content-Type: application/json" -d @connectionsStatusQuery.json` 
to execute their own query from the smart-api registration, I get nothing back.  May need to open a ticket with them about this.

**Comment by sstemann** [comment]
was working during just fix it
