### ISSUE TITLE
Update ARS Query Process Document for v1.0 TRAPI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#89]
https://docs.google.com/document/d/1zU0ljQ_gNDziZVLXYpVCKJ4HT1nu5lywyVN4MlMLfU8/edit?usp=sharing

**Comment by MarkDWilliams** [comment]
https://docs.google.com/document/d/18Xcq_yGxOPaaysqhUf-iLGa9Bkl2On9NHCAqkkoJ0QI/edit
Done
