### ISSUE TITLE
Allocate Server Per Steve Cox's Request

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#98]
https://drive.google.com/drive/folders/1xelbvQsn6Oph51iTyLkIhr_W6e2IEjAa?usp=sharing

**Comment by sstemann** [comment]
@stevencox  we'd like this request to be the next NCATS ITRB candidate

**Comment by stevencox** [comment]
Thanks @sstemann. What's our role in the review process? 

cc @YaphetKG @cbizon
